TOP=..

include $(TOP)/configure/CONFIG

INC += highfive/H5Attribute.hpp
INC += highfive/H5DataSet.hpp
INC += highfive/H5DataSpace.hpp
INC += highfive/H5DataType.hpp
INC += highfive/H5Easy.hpp
INC += highfive/H5Exception.hpp
INC += highfive/H5FileDriver.hpp
INC += highfive/H5File.hpp
INC += highfive/H5Group.hpp
INC += highfive/H5Object.hpp
INC += highfive/H5PropertyList.hpp
INC += highfive/H5Reference.hpp
INC += highfive/H5Selection.hpp
INC += highfive/H5Utility.hpp

INC += highfive/bits/H5Annotate_traits.hpp
INC += highfive/bits/H5Annotate_traits_misc.hpp
INC += highfive/bits/H5Attribute_misc.hpp
INC += highfive/bits/H5ConverterEigen_misc.hpp
INC += highfive/bits/H5Converter_misc.hpp
INC += highfive/bits/H5DataSet_misc.hpp
INC += highfive/bits/H5Dataspace_misc.hpp
INC += highfive/bits/H5DataType_misc.hpp
INC += highfive/bits/H5_definitions.hpp
INC += highfive/bits/H5Exception_misc.hpp
INC += highfive/bits/H5FileDriver_misc.hpp
INC += highfive/bits/H5File_misc.hpp
INC += highfive/bits/H5Iterables_misc.hpp
INC += highfive/bits/H5Node_traits.hpp
INC += highfive/bits/H5Node_traits_misc.hpp
INC += highfive/bits/H5Object_misc.hpp
INC += highfive/bits/H5Path_traits.hpp
INC += highfive/bits/H5Path_traits_misc.hpp
INC += highfive/bits/H5PropertyList_misc.hpp
INC += highfive/bits/H5ReadWrite_misc.hpp
INC += highfive/bits/H5Reference_misc.hpp
INC += highfive/bits/H5Selection_misc.hpp
INC += highfive/bits/H5Slice_traits.hpp
INC += highfive/bits/H5Slice_traits_misc.hpp
INC += highfive/bits/H5Utils.hpp

INC += highfive/h5easy_bits/H5Easy_Eigen.hpp
INC += highfive/h5easy_bits/H5Easy_misc.hpp
INC += highfive/h5easy_bits/H5Easy_opencv.hpp
INC += highfive/h5easy_bits/H5Easy_public.hpp
INC += highfive/h5easy_bits/H5Easy_scalar.hpp
INC += highfive/h5easy_bits/H5Easy_vector.hpp
INC += highfive/h5easy_bits/H5Easy_xtensor.hpp

include $(TOP)/configure/RULES
