TOP=../..

include $(TOP)/configure/CONFIG

PROD = merger

merger_LIBS += pvxs Com
merger_LIBS += common nttable

merger_SRCS += mergerMain.cpp tablebuffer.cpp taligntable.cpp

include $(TOP)/configure/RULES

